# -*- coding: utf-8 -*-
"""VoltageDivider.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LI0VxQzYS2rVHE16bmEhbbNymH8D4pN3
"""

VBE=0.7
k=1000
m=10^-3

VCC=24
RC=6800
RE=1.2*k
R2=15*k
R1=68*k
B=80

#Yaklaşık Analiz vs TAM Analiz

print ((B*RE)>=(10*R2))
if ((B*RE)>=(10*R2)):
  print("Yaklaşık Analiz")
else :
  print("Tam Analiz")

"""#Yaklaşık Analiz"""

VB=VCC*R2/(R1+R2)
print("VB: ",VB)
VE=VB-VBE
print("VE: ",VE)
IE=VE/RE
print("IE: ",IE)
IC=IE
print("IC: ",IC) 
IB=IC/B
print("IB: ",IB)
VCE=VCC-IC*RC-IE*RE
print("VCE: ",VCE)

# TAM ANALİZ



VTH=VCC*R2/(R1+R2)
print("Vth:" ,VTH)

RTH=R1*R2/(R1+R2)
print("Rth:" ,RTH)

IB=(VTH-VBE)/(RTH+(B+1)*RE)
print("IB:" ,IB)

IC=B*IB
print("IC:" ,IC)

IE=(B+1)*IB
print("IE:" ,IE)

VE=IE*RE
print("VE: ",VE)

VB=VE+VBE
print("VB: ",VB)

VCE=VCC-IC*RC-IE*RE
print("VCE: ",VCE)

VC=VCC-IC*RC
print("VC: ",VC)

PT=VCE*IC
print("PT: ",PT)

