#include <stdio.h>

void main() {
    int tercih;
    printf("Tarifi listelenecek yemek tarifini sec:\n1)Mercimek Corbasi\n2)Imambayildi\n3)Karniyarik\n4)Taze Fasulye\n\n#> ");
    scanf("%d", &tercih);
    
    switch (tercih) {
        case 1:
            printf("Kırmızı mercimek çorbası için sıvı yağı tencereye alınarak yemeklik doğranan soğanlar hafif pembeleşinceye kadar kavrulur. Daha sonra un ilave edilerek kısık ateşte kavurmaya devam edilir. Salça kullanılacak ise salça ilave edilir, kavrulduktan sonra küp küp doğranmış havuç ve iyice yıkanıp suyu süzülen mercimekler ilave edilir.Üzerine su eklenerek karıştırılır ve tencerenin kapağı kapatılır. Çorbamız kaynayana kadar orta ateşte, kaynadıktan sonra mercimekler ve havuçlar yumuşayana kadar ara ara karıştırılarak kısık ateşte pişirilir. Çorba piştikten sonra el blenderı ile güzelce ezilir. Eğer blenderiniz yoksa süzgeçten de geçirebilirsiniz.Karabiber, tuz ve isteğe bağlı olarak kimyon eklenir ve karıştırılır. 5 dakika daha pişirelerek ocaktan alınır.Kıvamı koyu gelirse size, bir miktar su ilave edilerek bir taşım kaynatılır. Bu arada küçük bir tavaya iki yemek kaşığı tereyağı alınır, kızdırılır ve bir tatlı kaşığı kırmızı toz biber eklenerek ocaktan alınır. Mercimek çorbası servis kasesine alındıktan sonra üzerine kırmızı biberli sos gezdirilir ve bir dilim limon ile servis edilir.");
        case 2:
            printf("Patlıcanları alacalı soyarak yarım saat kadar tuzlu suda bekletin. Ardından tuzunu akıtıp, havlu kağıt ile kurulayıp çevirerek her yönünü sıvı yağda kızartın. Yağın fazlasını alması için havlu kağıda alın. İç harcı için soğanları piyazlık doğrayın, 2-3 yemek kaşığı sıvı yağ ile ocağa alın ve kavurmaya başlayın. 5 dk. kadar soğanlar kavrulduktan sonra küçük doğranmış biberleri ve sarımsakları ilave edin, bir süre daha kavurun. Küçük doğranmış domates ve baharatları da ekleyerek domatesler suyunu biraz çekene kadar kavurmaya devam edin. İnce kıyılmış maydanozu ekleyerek ocaktan alın. Fırın kabına aldığınız patlıcanların üzerine boydan çizgi şeklinde kesin. İçlerine hazırladığınız iç harcından doldurun. Tavada kalan domatesli suyu fırın kabına dökün. Eğer su yeterli değilse domates sosu ile ya da çok az salça ile sos hazırlayın ve 190 derece ısıtılmış fırında pişirin.");
        case 3:
            printf("Patlıcanları çizgili soyup, yarım saat yağ çekmemesi için tuzlu suda bekletin. İyice yıkadıktan sonra suyunu havlu ile çektirin ve az yağda kızartın. 3 adet biberi de yağda kızartın. Daha sonra aynı tavada doğranmış soğanları kavurun, kıymayı ekleyerek bir müddet daha kavurun ve biberleri, sarımsağı ekleyerek 2 dakika daha kavurun. Küp küp doğramış olduğunuz 2 adet domatesi, tuzu, baharatları ekleyerek karıştırın. Üzerine bir çay bardağı su ekleyerek 5 dk kaynatın. Tepsiye patlıcanların ortalarını keserek yerleştirin ve bu kesiklerden patlıcanın içine bastırarak iç malzemesine yer açın ve malzeme ile patlıcanları doldurun. Doldurduğunuz patlıcanların üzerine ortadan ikiye kestiğiniz çeri domatesi ya da 1 adet domatesi eşit büyüklükte olacak şekilde paylaştırın ve kızarttığımız biberlerden birer tane koyun. Ayrı bir yerde 1 kaşık salçayı, 1 su bardağı sıcak suda ezerek patlıcanların aralarına dökün. Kıymalar çıkmasın diye üzerine dökmeyin. Daha sonra 170 derece de ısıttığınız fırına sürerek 20-25 dk pişirin. Dilerseniz bu işlemi pilav tenceresi gibi bir tencerede ocakta yapabilirsiniz. Aynı sürede tencerede de  pişecektir.");
        case 4:
            printf("Yeşil fasulye yemeği için öncelikle zeytinyağında yemeklik doğranmış soğanı pembeleşinceye kadar kavuralım. Ardından salça, doğranmış domatesler ve baharatları da ekleyip bir iki dakika kavuralım. Yıkayıp ortadan ikiye kestiğimiz ve dilimlediğimiz fasulyeleri ekleyip kavurmaya devam edelim. Fasulyeler renk değiştirip yumuşamaya başlayıncaya kadar kavuralım. Fasulyenin hızlı pişmesi için suyunu eklemeden iyice kavurmak önemli. Pişme süresi fasulyenin cinsine göre değişir, çatal kolay batıyorsa ve gıcırdamıyorsa yumuşamış demektir. Ben çalı fasulye kullandım bu arada, enli bir fasulye olduğu için ortadan da dikine kesiyorum, siz nasıl tercih ederseniz. Kavururken tencereyi kısık ateşe alıp kapağı kapatmayı unutmayın. Yeterince taze güzel bir fasulye ise su eklemeye gerek kalmadan kendi suyu ile kavrulurken bile pişebilir. Tuzunu ayarlayalım, yeşil fasulye yeterince kavrulunca sıcak suyunu ekleyip pişmeye bırakalım. Arada bir fasulye alıp ısırarak pişip pişmediğini kontrol edebilirsiniz. Ocağı kapatınca 15-20 dk ilk sıcaklığının çıkmasını bekleyelim. Taze fasulye yemeğini sıcak olarak da ılık olarak da servis edebilirsiniz. Zeytinyağlı gibi soğuk servis etmek isterseniz salça eklemeden aynı şekilde pişirebilirsiniz. Şimdiden afiyet olsun.");
    }
}